name: Deploy Chatbot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Display Current Directory
      run: |
        pwd
        ls -al

    - name: Setup AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11  # Updated to a more recent version

    - name: Terraform Init
      run: |
        ls -al ./ec2  # List contents of the ec2 directory
        cd ./ec2
        terraform init

    - name: Terraform Validate
      run: |
        cd ./ec2
        terraform validate

    - name: Build and Push Docker Image
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t htbBot:latest ./ecs
        docker push htbBot:latest

    - name: Terraform Init (ECS)
      run: |
        cd ./ecs
        terraform init

    - name: Terraform Validate (ECS)
      run: |
        cd ./ecs
        terraform validate

    - name: Terraform Plan
      run: |
        terraform plan ./ec2 ./ecs

    - name: Confirm Deployment
      run: |
        echo "This is a manual approval step."
        echo "Review the Terraform plan and confirm whether to deploy or not."

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      env:
        TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        TF_VAR_dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      run: terraform apply -auto-approve ./ec2 ./ecs

    - name: Confirm Destroy
      run: |
        echo "This is a manual approval step to destroy what was just created."
        echo "Review the Terraform plan and confirm whether to destroy or not."

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      env:
        TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        TF_VAR_dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      run: terraform destroy -auto-approve ./ec2 ./ecs
